name: Tag and Build

on:
  push:
    branches:
      - main
      - prod

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  tag-and-build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag.outputs.version }}
    env:
      CI_BRANCH: ${{ github.ref_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute next semantic version
        id: tag
        run: ./scripts/tag.sh

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Django image
        run: |
          docker build -t $DOCKERHUB_USERNAME/beatguessr-backend:$VERSION backend
          docker push $DOCKERHUB_USERNAME/beatguessr-backend:$VERSION

      - name: Build & push React image
        run: |
          docker build -t $DOCKERHUB_USERNAME/beatguessr-frontend:$VERSION frontend
          docker push $DOCKERHUB_USERNAME/beatguessr-frontend:$VERSION


  deploy:
    runs-on: ubuntu-latest
    needs: tag-and-build
    if: ${{ github.ref_name == 'prod' }}
    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          repository: JonathanGriffe/beatguessr-infra
          token: ${{ secrets.DEPLOY_PAT }}

      - name: Update infra
        env:
          VERSION: ${{ needs.tag-and-build.outputs.version }}
        run: |
          sed -i "s/appVersion: .*/appVersion: $VERSION/" helm/values.yaml
          sed -i "s/appVersion: .*/appVersion: $VERSION/" helm/Chart.yaml
          git add .

          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git commit -m "chore: update Docker images to $VERSION on prod"
          git push origin main