name: Tag and Build

on:
  push:
    branches:
      - main
      - prod

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  tag-and-build:
    runs-on: ubuntu-latest
    env:
      CI_BRANCH: ${{ github.ref_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute next semantic version
        run: ./scripts/tag.sh

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Django image
        run: |
          docker build -t $DOCKERHUB_USERNAME/beatguessr-backend:$VERSION backend
          docker push $DOCKERHUB_USERNAME/beatguessr-backend:$VERSION

      - name: Build & push React image
        run: |
          docker build -t $DOCKERHUB_USERNAME/beatguessr-frontend:$VERSION frontend
          docker push $DOCKERHUB_USERNAME/beatguessr-frontend:$VERSION
